src/objects/Survey_Question_Response__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Option_10__c</fullName>
        <description>The tenth option for a picklist/radio buttons.</description>
        <label>Option 10</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_1__c</fullName>
        <description>The first option for a picklist/radio buttons.</description>
        <label>Option 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_2__c</fullName>
        <description>The second option for a picklist/radio buttons.</description>
        <label>Option 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_3__c</fullName>
        <description>The third option for a picklist/radio buttons.</description>
        <label>Option 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_4__c</fullName>
        <description>The fourth option for a picklist/radio buttons.</description>
        <label>Option 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_5__c</fullName>
        <description>The fifth option for a picklist/radio buttons.</description>
        <label>Option 5</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_6__c</fullName>
        <description>The sixth option for a picklist/radio buttons.</description>
        <label>Option 6</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_7__c</fullName>
        <description>The seventh option for a picklist/radio buttons.</description>
        <label>Option 7</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_8__c</fullName>
        <description>The eighth option for a picklist/radio buttons.</description>
        <label>Option 8</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_9__c</fullName>
        <description>The ninth option for a picklist/radio buttons.</description>
        <label>Option 9</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Buttons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiCheckbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>The response from the user.</description>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Response__c</fullName>
        <label>Survey Response</label>
        <referenceTo>Survey_Response__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Complete_Date_Time__c</fullName>
        <label>Complete Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <label>Survey Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyAppController.cls
/*******************************************************************
 * Custom controller for the Survey Application. 
 *
 * Provides remoting methods to retrieve and save a survey response 
 * and its associated questions
 * 
 * Author : Keir Bowden
 *******************************************************************/
public with sharing class SurveyAppController {
	
	/* 
	 * Remote method to retrieve a survey response and questions based on the survey response code
	 */
	@RemoteAction
	public static Survey_Response__c GetSurveyResponse(String code)
	{
		Survey_Response__c result=null;
		
		// query the response and question data for the supplied code
		List<Survey_Response__c> responses=[select id, Name, Description__c, Code__c, Complete__c, Complete_Date_Time__c, 
													Start_Date_Time__c, Survey_Name__c,
													(select id, Question_Text__c, Question_Type__c, Index__c, Response__c,
														Option_1__c, Option_2__c, Option_3__c, Option_4__c, Option_5__c, 
														Option_6__c, Option_7__c, Option_8__c, Option_9__c, Option_10__c,
														Help_Text__c, Survey_Response__c
													from Survey_Question_Responses__r
													order by Index__c ASC)
											from Survey_Response__c
					 						where Code__c=:code];


		System.debug('### Responses.size = ' + responses.size());
		
		// there should be exactly one match - if this is not the case throw an exception
		if (responses.size()!=1)
		{
			throw new SurveyException('No matching survey found');
		}
		else
		{
			// mark the start time for the survey as now
			responses[0].Start_Date_Time__c=System.now();
			update responses[0];
			
			// set the result to the single matching survey response
			result=responses[0];
		}
		
		return result;
	}
	
	/* 
	 * Remote method to save the question responses for a survey.
	 * Note that the survey response record is not passed to this method, as the end user
	 * cannot change any of the fields in that record so it would be overhead on the request.
	 */
	@RemoteAction
	public static void SaveSurveyResponse(List<Survey_Question_Response__c> qrs)
	{
		// write the question responses to the database
		update qrs;
		
		// get the id of the first element in the array - this will be used to retrieve the associated survey response
		Id qrId=qrs[0].Id;
		
		// pull back the survey response id for the question response
		Survey_Question_Response__c qr=[select id, Survey_Response__c from Survey_Question_Response__c where id=:qrId];
		
		// construct a new survey response record using the id of the existing response - this allows update of the record
		// without retrieving the details from the database.
		// set the survey response as complete and mark the end time as now 
		Survey_Response__c sr=new Survey_Response__c(id=qr.Survey_Response__c,
													Complete__c=true,
													Complete_Date_Time__c=System.now());
			
		update sr;
	}	
	
	// custom survey exception - allows an exception to be explicitly thrown from the controller 
	public class SurveyException extends Exception {}
	
}