src/objects/Survey__c.object
<CustomObject>
    <description>Template for a survey, made up of a number of questions.  A survey response is associated with a single user and is cloned from this as required.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <description>Template for a survey question. When a survey response is created, the associated questions are copied to question responses.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Help information - accessible from the question response.</description>
        <label>Help Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Option_10__c</fullName>
        <description>The tenth option for a picklist/radio buttons.</description>
        <label>Option 10</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_1__c</fullName>
        <description>The first option for a picklist/radio buttons.</description>
        <label>Option 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_2__c</fullName>
        <description>The second option for a picklist/radio buttons.</description>
        <label>Option 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_3__c</fullName>
        <description>The third option for a picklist/radio buttons.</description>
        <label>Option 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_4__c</fullName>
        <description>The fourth option for a picklist/radio buttons.</description>
        <label>Option 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_5__c</fullName>
        <description>The fifth option for a picklist/radio buttons.</description>
        <label>Option 5</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_6__c</fullName>
        <description>The sixth option for a picklist/radio buttons.</description>
        <label>Option 6</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_7__c</fullName>
        <description>The seventh option for a picklist/radio buttons.</description>
        <label>Option 7</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_8__c</fullName>
        <description>The eighth option for a picklist/radio buttons.</description>
        <label>Option 8</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_9__c</fullName>
        <description>The ninth option for a picklist/radio buttons.</description>
        <label>Option 9</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Buttons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiCheckbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Question_Response__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Option_10__c</fullName>
        <description>The tenth option for a picklist/radio buttons.</description>
        <label>Option 10</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_1__c</fullName>
        <description>The first option for a picklist/radio buttons.</description>
        <label>Option 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_2__c</fullName>
        <description>The second option for a picklist/radio buttons.</description>
        <label>Option 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_3__c</fullName>
        <description>The third option for a picklist/radio buttons.</description>
        <label>Option 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_4__c</fullName>
        <description>The fourth option for a picklist/radio buttons.</description>
        <label>Option 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_5__c</fullName>
        <description>The fifth option for a picklist/radio buttons.</description>
        <label>Option 5</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_6__c</fullName>
        <description>The sixth option for a picklist/radio buttons.</description>
        <label>Option 6</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_7__c</fullName>
        <description>The seventh option for a picklist/radio buttons.</description>
        <label>Option 7</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_8__c</fullName>
        <description>The eighth option for a picklist/radio buttons.</description>
        <label>Option 8</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_9__c</fullName>
        <description>The ninth option for a picklist/radio buttons.</description>
        <label>Option 9</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Buttons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiCheckbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_Response__c</fullName>
        <label>Survey Response</label>
        <referenceTo>Survey_Response__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <label>Survey Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyUtils.cls
public without sharing class SurveyUtils 
{
	public static Survey_Response__c CreateSurveyResponse(Id chosenSurveyId, Id contactId)
	{
		List<Contact> contacts=[select id, FirstName, LastName, Email from Contact where id=:contactId];
		Contact cont;
		if (contacts.size()>0)
		{
			cont=contacts[0];
		}
		else
		{
			return null;
		}
		
		List<Survey__c> surveys=[select id, Name, Description__c from Survey__c where id = :chosenSurveyId];
		Survey__c survey;
		if (surveys.size()>0)
		{
			survey=surveys[0];
		}
		else
		{
			return null;
		}
		
		Survey_Response__c sr=new Survey_Response__c();
		sr.Contact__c=cont.id;
		sr.Name=survey.Name + '- ' + cont.FirstName + ' ' + cont.LastName;
		sr.Survey_Name__c=survey.Name;
		sr.Description__c=survey.Description__c;
		
		DateTime now = System.now();         
        String formattednow = now.formatGmt('yyyy-MM-dd')+'T'+ now.formatGmt('HH:mm:ss')+'.'+now.formatGMT('SSS')+'Z';         
        String canonical = sr.id + sr.Name + formattednow;                        
        Blob bsig = Crypto.generateDigest('MD5', Blob.valueOf(canonical));         
        String token =  EncodingUtil.base64Encode(bsig);                 
        if(token.length() > 255) 
        { 
        	token =  token.substring(0,254); 
        }
                
        sr.Code__c = Encodingutil.urlEncode(token, 'UTF-8').replaceAll('%','_');		
        insert sr;
		
		List<Survey_Question_Response__c> sqrs=new List<Survey_Question_Response__c>();
		for (Survey_Question__c sq : [select id, Name, Question_Text__c, Question_Type__c, Index__c,
									Option_1__c, Option_2__c, Option_3__c, Option_4__c, Option_5__c,
									Option_6__c, Option_7__c, Option_8__c, Option_9__c, Option_10__c,
									Help_Text__c
									from Survey_Question__c
									where Survey__c=:survey.id
									order by Index__c])
		{
			Survey_Question_Response__c sqr=new Survey_Question_Response__c();
			sqr.Question_Text__c=sq.Question_Text__c;
			sqr.Question_Type__c=sq.Question_Type__c;
			sqr.Help_Text__c=sq.Help_Text__c;
			sqr.Index__c=sq.Index__c;
			sqr.Option_1__c=sq.Option_1__c;
			sqr.Option_2__c=sq.Option_2__c;
			sqr.Option_3__c=sq.Option_3__c;
			sqr.Option_4__c=sq.Option_4__c;
			sqr.Option_5__c=sq.Option_5__c;
			sqr.Option_6__c=sq.Option_6__c;
			sqr.Option_7__c=sq.Option_7__c;
			sqr.Option_8__c=sq.Option_8__c;
			sqr.Option_9__c=sq.Option_9__c;
			sqr.Option_10__c=sq.Option_10__c;
			sqr.Survey_Response__c=sr.id;
			sqrs.add(sqr);
		}
		
		insert sqrs;
		
		return sr;
	}

	public static Id GetContactId(String emailAddress)
	{
		
		Id contid=null;
		
		List<Contact> contacts=[select id, Email from Contact where Email=:emailAddress];
		if (contacts.size()>0)
		{
			contId=contacts[0].id;
		}
		else
		{
			Contact cont=new Contact(Email=emailAddress);
			List<Account> accounts=[select id from Account where name='BrightGen'];
			Account acc;
			if (accounts.size()==0)
			{
				acc=new Account(name='BrightGen');
				insert acc;
			}
			else
			{
				acc=accounts[0];
			}
			
			cont.AccountId=acc.id;
			if (String.IsBlank(cont.FirstName))
			{
				cont.FirstName=cont.Email;
			}
			if (String.IsBlank(cont.LastName))
			{
				cont.LastName=cont.Email;
			}
			insert cont;
			contId=cont.id;
		}
		
		return contId;
	}
}