src/objects/Survey__c.object
<CustomObject>
    <description>Template for a survey, made up of a number of questions.  A survey response is associated with a single user and is cloned from this as required.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateSurveyResponseController.cls
public with sharing class CreateSurveyResponseController 
{
	public Id surveyId {get; set;}
	public String surveyDescription {get; set;}
	public List<SelectOption> surveys {get; set;}
	private Map<Id, Survey__c> surveysById {get; set;}
	public Survey_Response__c rsp {get; set;}
	
	// extension constructor - not used, but allows this page to override
	// the new survey response behaviour
	public CreateSurveyResponseController(ApexPages.StandardController stdCtrl)
	{
		this();
	}
	
	public CreateSurveyResponseController()
	{
		surveys=new List<SelectOption>();
		surveysById=new Map<Id, Survey__c>();
		for (Survey__c srv : [select id, Name, Description__c from Survey__c])
		{
			if (null==surveyId)
			{
				surveyId=srv.id;
				surveyDescription=srv.Description__c;
			}
			surveys.add(new SelectOption(srv.Id, srv.Name));
			surveysById.put(srv.id, srv);
		}
		
		rsp=new Survey_Response__c();
	}
	
	public void surveyChanged()
	{
		surveyDescription=surveysById.get(surveyId).Description__c;
	}
	
	public PageReference Save()
	{
		Survey_Response__c result=SurveyUtils.CreateSurveyResponse(surveyId, rsp.Contact__c);
		
		return new PageReference('/' + result.id);
	}
}